FROM node:18.15.0-alpine3.17

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install

ADD .eslintrc.cjs .prettierrc.json index.html jsconfig.json vite.config.js ./

CMD ["npm", "run", "dev"]
